version: 2

refrences:
  cache-options: &cache-options
    key: package-cache-{{ checksum "package-lock.json" }}

jobs:
  build:
    docker:
      - image: circleci/node:12
      - image: redis:4
    steps:
      - checkout
      - restore_cache:
          <<: *cache-options
      - run:
          name: npm-install
          command: npm install
      - save_cache:
          <<: *cache-options
          paths:
            - ./node_modules

  test:
    docker:
      - image: circleci/node:12
      - image: redis:4
    steps:
      - checkout
      - restore_cache:
          <<: *cache-options
      - run:
          name: test
          command: npm run test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
